#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#  D E F I N I T I O N   O F   Y O U R   A C Q U I S I T I O N    #
#  D I G I T I Z E R   &   C O I N C I D E N C E   S H O R T E R  #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#	A D D E R
/gate/digitizer/Singles/insert adder


#       R E A D O U T 
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 3


#      E N E R G Y   B L U R R I N G
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.26
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV


#       E N E R G Y   C U T
/gate/digitizer/Singles/insert                              thresholder
/gate/digitizer/Singles/thresholder/setThreshold            250 keV
/gate/digitizer/Singles/insert                              upholder
/gate/digitizer/Singles/upholder/setUphold                  750 keV


#       D E A D    T I M E 
/gate/digitizer/Singles/insert deadtime
/gate/digitizer/Singles/deadtime/setDeadTime 3 us
/gate/digitizer/Singles/deadtime/setMode paralysable
/gate/digitizer/Singles/deadtime/chooseDTVolume block


#       E N E R G Y     W I N D O W
/gate/digitizer/name                                EWindow
/gate/digitizer/insert                              singleChain
/gate/digitizer/EWindow/setInputName                Singles

# 50 % energy window
/gate/digitizer/EWindow/insert                      thresholder
/gate/digitizer/EWindow/thresholder/setThreshold    380 keV
/gate/digitizer/EWindow/insert                      upholder
/gate/digitizer/EWindow/upholder/setUphold          640 keV



#	    C O I N C I D E N C E    S O R T E R 
/gate/digitizer/Coincidences/setInputName           EWindow
/gate/digitizer/Coincidences/setWindow              10 ns
/gate/digitizer/Coincidences/minSectorDifference    1
/gate/digitizer/Coincidences/describe


/gate/digitizer/name                                delay
/gate/digitizer/insert                              coincidenceSorter
/gate/digitizer/delay/setInputName                  EWindow
/gate/digitizer/delay/setWindow                     10. ns
/gate/digitizer/delay/setOffset                     500. ns
/gate/digitizer/delay/minSectorDifference    1
/gate/digitizer/delay/describe


/gate/digitizer/name                                	finalCoinc
/gate/digitizer/insert                              	coincidenceChain
/gate/digitizer/finalCoinc/addInputName             	delay
/gate/digitizer/finalCoinc/addInputName             	Coincidences
/gate/digitizer/finalCoinc/describe
/gate/digitizer/finalCoinc/usePriority              	false
#/gate/digitizer/finalCoinc/insert deadtime
#/gate/digitizer/finalCoinc/deadtime/setDeadTime		1.2 us
#/gate/digitizer/finalCoinc/deadtime/setMode nonparalysable
